# Configurações do Servidor
server.port=8080
spring.application.name=backend-sistema

# Configurações do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Tinderdb
spring.datasource.username=postgres
spring.datasource.password=gabriel12@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=8f3Q!9zM2R@k#6sD1P0wE4T7yXH$LZcAqVJmN5uK
jwt.expiration=3600000
jwt.refresh-expiration=604800000
# Configurações de Log
logging.level.com.seuapp=DEBUG
logging.level.org.springframework.security=DEBUG

# CORS (ajuste conforme necessário)
cors.allowed-origins=http://localhost:3000,http://localhost:4200