# Configurações do Servidor
server.port=8080
spring.application.name=backend-sistema

spring.datasource.url=jdbc:postgresql://localhost:5432/Tinderdb
spring.datasource.username=postgres
spring.datasource.password=gabriel12@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret (MUDE ISSO EM PRODUÇÃO!)
jwt.secret=sua-chave-secreta-muito-longa-e-segura-aqui-minimo-256-bits
jwt.expiration=86400000

# Configurações de Log
logging.level.com.seuapp=DEBUG
logging.level.org.springframework.security=DEBUG

# CORS (ajuste conforme necessário)
cors.allowed-origins=http://localhost:3000,http://localhost:4200

# RabbitMQ
spring.rabbitmq.host=beaver.rmq.cloudamqp.com
spring.rabbitmq.virtual-host=ovhjehds
spring.rabbitmq.username=ovhjehds
spring.rabbitmq.password=PJAgVSEF-nzRUWN5DXXl8C9etBv-pWcG

# Porta depende de TLS ou não:
spring.rabbitmq.port=5671
spring.rabbitmq.ssl.enabled=true

# Filas RabbitMQ
rabbitmq.queue.chat=chat.messages
rabbitmq.queue.match=match.notifications
rabbitmq.queue.email=email.queue
rabbitmq.queue.image=image.processing
rabbitmq.exchange.main=matchapp.exchange